### ISSUE TITLE
Error in ff_samp[, "File2"]: subscript out of bounds

### ISSUE THREAD

**Issue by EST09** [prybakowska/CyTOF_analysis_Pipeline1#3]
Hi, 

Thank you so much for putting this together!
I'm just trying to run plot_batch but I get the error `Error in ff_samp[, "File2"]: subscript out of bounds`

I've tried running the code outside the function and parallelisation to understand (just for normalised files so far: `files = files_list[["files_after_norm" ]]`) and my ff_samp has colnames 

`"marker 1 e.g. CD112Di, marker 2 ................ , File, File_scattered, Original_ID"`

I was just wondering where File2 colname comes from/how to get it in ff_samp please? Would it just be the equivalent of File in my case? Thank you!

Best wishes, 
Emily

**Comment by prybakowska** [comment]
Dear Emily, Thank you for your email. Do you work with the data acquired in aliquots? And did you run all the previous steps? Did you run the function “extract_pctgs_msi_per_flowsom” before plotting the batch? Did you try to change the function and see if it works with “File”? If you run “extract_pctgs_msi_per_flowsom” and it is working with “File” it means that there is a bug in the code I can fix it first thing in the morning. Can you also make it an issue in GitHub? Please let me know!Best, Paulina From: EST09Sent: Friday, November 18, 2022 11:49 AMTo: prybakowska/CyTOF_analysis_Pipeline1Cc: SubscribedSubject: [prybakowska/CyTOF_analysis_Pipeline1] Error in ff_samp[, "File2"]: subscript out of bounds (Issue #3) Hi,Thank you so much for putting this together!I'm just trying to run plot_batch but I get the error Error in ff_samp[, "File2"]: subscript out of boundsI've tried running the code outside the function and parallelisation to understand (just for normalised files so far: files = files_list[["files_after_norm" ]]) and my ff_samp has colnames"marker 1 e.g. CD112Di, marker 2 ............... , File, File_scattered, Original_ID"I was just wondering where File2 colname comes from/how to get it in ff_samp please? Would it just be the equivalent of File in my case? Thank you!Best wishes,Emily—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by EST09** [comment]
`Dear Emily, Thank you for your email. Do you work with the data acquired in aliquots? And did you run all the previous steps? Did you run the function “extract_pctgs_msi_per_flowsom” before plotting the batch? Did you try to change the function and see if it works with “File”? If you run “extract_pctgs_msi_per_flowsom” and it is working with “File” it means that there is a bug in the code I can fix it first thing in the morning. Can you also make it an issue in GitHub? Please let me know!Best, Paulina`


Hi Paulina, 

Thank you so much for the quick response!

I haven't run all the other steps - I just liked your plot_batch function and wanted to use it as a stand alone function so that might be the issue. I also didn't want to wait for someone to install CytoQP on our RStudio cloud so I've copied and pasted directly from plot_batch_effect.R and utils.R which hopefully shouldn't but might be another issue. 

If I substitute File for File2 it seems to works - would you go for File rather than File_scatter or Original_ID? 

I also had to change 

`png(file.path(norm_dir, "batch_effect.png"),
      width = length(plots)*1500,
      height = 1500, res = 300)
  gridExtra::grid.arrange(grobs = plots, ncol = 2)`

to 

`png(file.path(out_dir, "batch_effect.png"),
      width = length(plots)*1500,
      height = 1500, res = 300)
  gridExtra::grid.arrange(grobs = plots, ncol = 2)`

I'll go through `extract_pctgs_msi_per_flowsom` and see whether it takes File. 

Sorry all of this might just be because I'm picking and choosing functions from your package. Thanks again!

Best wsihes, 
Emily

**Comment by prybakowska** [comment]
So with “File” you get what you need is that correct? Yes, I would definitely go for the “File” because this is the ID of the actual FCS file. Let me know if you have any other issues!Paulina  From: EST09Sent: Friday, November 18, 2022 12:53 PMTo: prybakowska/CyTOF_analysis_Pipeline1Cc: prybakowska; CommentSubject: Re: [prybakowska/CyTOF_analysis_Pipeline1] Error in ff_samp[, "File2"]: subscript out of bounds (Issue #3) Dear Emily, Thank you for your email. Do you work with the data acquired in aliquots? And did you run all the previous steps? Did you run the function “extract_pctgs_msi_per_flowsom” before plotting the batch? Did you try to change the function and see if it works with “File”? If you run “extract_pctgs_msi_per_flowsom” and it is working with “File” it means that there is a bug in the code I can fix it first thing in the morning. Can you also make it an issue in GitHub? Please let me know!Best, PaulinaHi Paulina,Thank you so much for the quick response!I haven't run all the other steps - I just liked your plot_batch function and wanted to use it as a stand alone function so that might be the issue. I also didn't want to wait for someone to install CytoQP on our RStudio cloud so I've copied and pasted directly from plot_batch_effect.R and utils.R which hopefully shouldn't but might be another issue.If I substitute File for File2 it seems to works - would you go for File rather than File_scatter or Original_ID?I also had to changepng(file.path(norm_dir, "batch_effect.png"), width = length(plots)*1500, height = 1500, res = 300) gridExtra::grid.arrange(grobs = plots, ncol = 2)topng(file.path(out_dir, "batch_effect.png"), width = length(plots)*1500, height = 1500, res = 300) gridExtra::grid.arrange(grobs = plots, ncol = 2)I'll go through extract_pctgs_msi_per_flowsom and see whether it takes File.Sorry all of this might just be because I'm picking and choosing functions from your package. Thanks again!Best wsihes,Emily—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by EST09** [comment]
`-->So with “File” you get what you need is that correct? Yes, I would definitely go for the “File” because this is the ID of the actual FCS file. Let me know if you have any other issues!Paulina `

Yep - thank you so much!

Best wishes, 
Emily
